const DATA_SCHEMA = 'prj_X-ZoVQv6LKXT';
const originalFetch = globalThis.fetch;
globalThis.fetch = (input: any, init: any = {}) => {
  const url = typeof input === 'string'
    ? input
    : input?.url?.toString?.() || input?.toString?.() || '';

  if (url.includes('/rest/v1/')) {
    const headers = new Headers(init.headers || {});
    headers.set('Accept-Profile', DATA_SCHEMA);
    headers.set('Content-Profile', DATA_SCHEMA);
    init = { ...init, headers };
  }

  return originalFetch(input, init);
};
// Auto-generated by Famous build (CRM cron dispatcher).
// Do not edit by hand â€” changes will be overwritten on the next CRM
// schema sync. Owned by the CRM tab.
//
// Triggered by DatabasePad cron jobs whose name starts with "crm-"
// (see lib/crm-cron-sync.ts in the builder repo). Forwards the
// payload to the builder's /api/crm/{projectId}/cron/dispatch
// endpoint with an HMAC-signed body.

const PROJECT_ID = "6912a1d2ea97d4e30b03d36a";
const BUILDER_URL = "https://famous.ai";

async function hmacSha256Hex(secret, message) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sigBuf = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  const bytes = new Uint8Array(sigBuf);
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i].toString(16).padStart(2, "0");
  }
  return hex;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "*",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "method_not_allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  const secret = Deno.env.get("CRM_DISPATCH_SECRET");
  if (!secret) {
    return new Response(JSON.stringify({ error: "secret_not_configured" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }

  const raw = await req.text();
  const ts = Math.floor(Date.now() / 1000).toString();
  const sig = await hmacSha256Hex(secret, ts + "." + raw);

  const upstream = await fetch(
    BUILDER_URL + "/api/crm/" + PROJECT_ID + "/cron/dispatch",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-crm-cron-timestamp": ts,
        "x-crm-cron-signature": "sha256=" + sig,
      },
      body: raw,
    }
  );

  const text = await upstream.text();
  return new Response(text, {
    status: upstream.status,
    headers: { "Content-Type": "application/json" },
  });
});

